
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: users-status-check
          #uri: http://localhost:9090
          uri: lb://resources
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: albums
          uri: lb://albums
          predicates:
            - Path=/albums
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

        - id: photos
          uri: lb://Photos
          predicates:
            - Path=/photos
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie